version: 1.2.{build}

# branches to build
branches:
  except:
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# enable patching of .NET Standard csproj.* files
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: "1.2.{build}"
  file_version: '{version}'
  informational_version: '{version}'

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Mustachio.sln --verbosity m

build_script:
  - cmd: dotnet build ./Mustachio.sln -c Release
  
#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - '**\*.Tests.dll'

after_test:
  - ps: nuget.exe pack ./Mustachio/Mustachio.nuspec -Version $env:APPVEYOR_BUILD_VERSION

artifacts:
  # pushing all *.nupkg files in directory
  - path: '*.nupkg'

  #---------------------------------#
  #     deployment configuration    #
  #---------------------------------#

  # providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
  # provider names are case-sensitive!

deploy:
  # Deploying to NuGet feed
  - provider: NuGet
    api_key:
      secure: sKvwxg5DmHjLtvBb0YEo9M+JYle83QWCDiGWfWOGOP6mQflp48qg1C5MJeNCw9cE
    skip_symbols: true
    on:
      appveyor_repo_tag: true
